# Generated by Django 6.0.5 on 2026-05-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pdesc', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('pcategory', models.CharField(max_length=30)),
                ('pqauntity', models.IntegerField()),
                ('trending', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
                ('pimage', models.ImageField(default='dfimg.jpg.jpeg', upload_to='uploads/')),
            ],
        ),
    ]
