# Generated by Django 6.0.5 on 2026-05-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
