# Generated by Django 6.0.5 on 2026-05-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cartmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='tota_price',
            new_name='total_price',
        ),
    ]
